### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by cevin15** [satori/git-svn-fast-import#1]
First，thank you for the project. It's great.
When I am import a svn project by using this project, a problem is encountered.
This is my operating logs.
```
[root@68cf358f7acf oschina.git]# git-svn-fast-import /home/data/svn/oschina/
progress Skipped revision 0
/root/opt/bin/git-svn-fast-import: line 99:   606 Segmentation fault      svn-fast-export /home/data/svn/oschina/
fatal: stream ends early
fast-import: dumping crash report to .git/fast_import_crash_607
Unpacking objects: 100% (2/2), done.
```
I have no idea how to fix it. I hope you can solve the problem, thank you very much.

**Comment by fcharlie** [comment]
Bug line: 
https://github.com/satori/git-svn-fast-import/blob/dbbd65bf7b91a26a2c901df490ceb487f216b12e/export.c#L342

When one Subversion repositroy has subdir (like git submodule) checksum is `NULL` no skipped.

@satori

**Comment by satori** [comment]
This project is not supported unfortunately and I don't have an access to subversion repository on which conversion I was working back in the day. This codebase is basically as-is with some tests provided.

Thanks for your interest though.
